<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class WPinyin extends Model {

    protected $table = 'pinyin';

    public $timestamps = false;

    /*
     * 获得拼音音节
     */
    public static function getAllAndCache()
    {
        if (\Cache::has(\App\WRef::CACHE_KEY_PINYIN_IDX)) {
            $pinyins = explode('|', \Cache::get(\App\WRef::CACHE_KEY_PINYIN_IDX));
        } else {
            $pinyins = [];
            foreach (self::all() as $pinyin) {
                $pinyins[] = $pinyin->key;
            }

            \Cache::forever(\App\WRef::CACHE_KEY_PINYIN_IDX, implode('|', $pinyins));
        }

        return $pinyins;
    }

    /**
     * 获得拼音音节表
     */
    public static function getPinyinIndex()
    {
        return array_merge(self::$pinyinIndex);
    }

    /**
     * 贵金属特殊拼音音节
     */
    public static function getMetalPinyinIndex()
    {
        return self::$metalPinyinIndex;
    }

    /**
     * 不满足全拼规则词根
     *
     * @var array
     */
    private static $metalPinyinIndex = [
        '9k',
        '14k',
        '18k',
        '22k',
        '999.5',
        '999.99',
        '800',
        '925',
        '990',
        '999',
        '9995',
        '9999',
        '850',
        '900',
        '916',
        '950',
        '990',
        '999',
        '500',
        '950',
        '990',
        '999',

        // 黄金
        'Au375',
        'G375',
        '9KJ',
        '14KJ',
        'Au585',
        'G585',
        '18KJ',
        'Au750',
        'G750',
        'G18K',
        '22KJ',
        'Au916',
        'G916',
        '22K',
        'ZJ',
        'Au990',
        'G990',
        'Au995',
        'G995',
        'QZJ',
        'Au999',
        'G999',
        'Au999.5',
        'G999.5',
        'Au999.9',
        'G999.9',
        'WCJ',

        // Ag 银
        // 银925
        'Ag925',
        'S925',
        // 足银
        'Ag990',
        'S990',
        'ZY',
        // 千足银
        'Ag999',
        'S999',
        'QZY',
        // 银999.5
        'Ag999.5',
        'S999.5',
        // 银999.9
        'Ag999.9',
        'S999.9',

        // 铂金
        // 铂850
        'Pt850',
        // 铂900
        'Pt900',
        // 铂950
        'Pt950',
        // 铂990
        'Pt990',
        'ZB',
        // 铂999
        'Pt999',
        'QZB',
        // 铂999.5
        'Pt999.5',

        // 钯金
        'Pd500',
        'Pd950',
        'Pd990',
        'Pd999',

    ];

    /**
     * 拼音音节索引
     *
     * @var array
     */
    private static $pinyinIndex = [
        'a',
        'ai',
        'an',
        'ang',
        'ao',
        'ba',
        'bai',
        'ban',
        'bang',
        'bao',
        'bei',
        'ben',
        'beng',
        'bi',
        'bian',
        'biao',
        'bie',
        'bin',
        'bing',
        'bo',
        'bu',
        'bun',
        'ca',
        'cai',
        'can',
        'cang',
        'cao',
        'ce',
        'cen',
        'ceng',
        'cha',
        'chai',
        'chan',
        'chang',
        'chao',
        'che',
        'chen',
        'cheng',
        'chi',
        'chong',
        'chou',
        'chu',
        'chua',
        'chuai',
        'chuan',
        'chuang',
        'chui',
        'chun',
        'chuo',
        'ci',
        'cong',
        'cou',
        'cu',
        'cuan',
        'cui',
        'cun',
        'cuo',
        'da',
        'dai',
        'dan',
        'dang',
        'dao',
        'de',
        'den',
        'dei',
        'deng',
        'di',
        'dia',
        'dian',
        'diao',
        'die',
        'ding',
        'diu',
        'dong',
        'dou',
        'du',
        'duan',
        'dui',
        'dun',
        'duo',
        'e',
        'ei',
        'en',
        'eng',
        'er',
        'fa',
        'fan',
        'fang',
        'fei',
        'fen',
        'feng',
        'fo',
        'fou',
        'fu',
        'ga',
        'gai',
        'gan',
        'gang',
        'gao',
        'ge',
        'gei',
        'gen',
        'geng',
        'gi',
        'gong',
        'gou',
        'gu',
        'gua',
        'guai',
        'guan',
        'guang',
        'gui',
        'gun',
        'guo',
        'ha',
        'hai',
        'han',
        'hang',
        'hao',
        'he',
        'hei',
        'hen',
        'heng',
        'hong',
        'hou',
        'ho',
        'hu',
        'hua',
        'huai',
        'huan',
        'huang',
        'hui',
        'hun',
        'huo',
        'ji',
        'jia',
        'jian',
        'jiang',
        'jiao',
        'jie',
        'jin',
        'jing',
        'jiong',
        'jiu',
        'ju',
        'juan',
        'jue',
        'jun',
        'ka',
        'kai',
        'kan',
        'kang',
        'kao',
        'ke',
        'ken',
        'keng',
        'kei',
        'kong',
        'kou',
        'ku',
        'kua',
        'kuai',
        'kuan',
        'kuang',
        'kui',
        'kun',
        'kuo',
        'la',
        'lai',
        'lan',
        'lang',
        'lao',
        'le',
        'lei',
        'leng',
        'li',
        'lia',
        'lian',
        'liang',
        'liao',
        'lie',
        'lin',
        'ling',
        'liu',
        'lo',
        'long',
        'lou',
        'lu',
        'lv',
        'luan',
        'lue',
        'lve',
        'lun',
        'luo',
        'm',
        'ma',
        'mai',
        'man',
        'mang',
        'mao',
        'me',
        'mei',
        'men',
        'meng',
        'mi',
        'mian',
        'miao',
        'mie',
        'min',
        'ming',
        'miu',
        'mo',
        'mou',
        'mu',
        'na',
        'nai',
        'nan',
        'nang',
        'nao',
        'ne',
        'nei',
        'nen',
        'neng',
        'ng',
        'ni',
        'nian',
        'niang',
        'niao',
        'nie',
        'nin',
        'ning',
        'niu',
        'nong',
        'nou',
        'nu',
        'nv',
        'nuan',
        'nve',
        'nuo',
        'nun',
        'o',
        'ou',
        'pa',
        'pai',
        'pan',
        'pang',
        'pao',
        'pei',
        'pen',
        'peng',
        'pi',
        'pian',
        'piao',
        'pie',
        'pin',
        'ping',
        'po',
        'pou',
        'pu',
        'qi',
        'qia',
        'qian',
        'qiang',
        'qiao',
        'qie',
        'qin',
        'qing',
        'qiong',
        'qiu',
        'qu',
        'quan',
        'que',
        'qun',
        'ran',
        'rang',
        'rao',
        're',
        'ren',
        'reng',
        'ri',
        'rong',
        'rou',
        'ru',
        'ruan',
        'rui',
        'run',
        'ruo',
        'sa',
        'sai',
        'san',
        'sang',
        'sao',
        'se',
        'sen',
        'seng',
        'sha',
        'shai',
        'shan',
        'shang',
        'shao',
        'she',
        'shei',
        'shen',
        'sheng',
        'shi',
        'shou',
        'shu',
        'shua',
        'shuai',
        'shuan',
        'shuang',
        'shui',
        'shun',
        'shuo',
        'si',
        'song',
        'sou',
        'su',
        'suan',
        'sui',
        'sun',
        'suo',
        'ta',
        'tai',
        'tan',
        'tang',
        'tao',
        'te',
        'teng',
        'ti',
        'tian',
        'tiao',
        'tie',
        'ting',
        'tong',
        'tou',
        'tu',
        'tuan',
        'tui',
        'tun',
        'tuo',
        'uu',
        'wa',
        'wai',
        'wan',
        'wang',
        'wei',
        'wen',
        'weng',
        'wo',
        'wu',
        'xi',
        'xia',
        'xian',
        'xiang',
        'xiao',
        'xie',
        'xin',
        'xing',
        'xiong',
        'xiu',
        'xu',
        'xuan',
        'xue',
        'xun',
        'ya',
        'yan',
        'yang',
        'yao',
        'ye',
        'yi',
        'yin',
        'ying',
        'yo',
        'yong',
        'you',
        'yu',
        'yuan',
        'yue',
        'yun',
        'za',
        'zai',
        'zan',
        'zang',
        'zao',
        'ze',
        'zei',
        'zen',
        'zeng',
        'zha',
        'zhai',
        'zhan',
        'zhang',
        'zhao',
        'zhe',
        'zhei',
        'zhen',
        'zheng',
        'zhi',
        'zhong',
        'zhou',
        'zhu',
        'zhua',
        'zhuai',
        'zhuan',
        'zhuang',
        'zhui',
        'zhun',
        'zhuo',
        'zi',
        'zong',
        'zou',
        'zu',
        'zuan',
        'zui',
        'zun',
        'zuo',
    ];
}
